# Generated by Django 5.1.3 on 2025-01-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rec',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
