# Generated by Django 5.1.3 on 2025-01-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_rec_transaction_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_no',
            new_name='rec_account_no',
        ),
    ]
